/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as ConnectChatgptRouteImport } from './routes/connect.chatgpt'
import { Route as ConnectConvexRouteImport } from './routes/connect.convex'
import { Route as ConnectGithubRouteImport } from './routes/connect.github'
import { Route as ConnectImessageRouteImport } from './routes/connect.imessage'
import { Route as ConnectXchatRouteImport } from './routes/connect.xchat'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectChatgptRoute = ConnectChatgptRouteImport.update({
  id: '/connect/chatgpt',
  path: '/connect/chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectConvexRoute = ConnectConvexRouteImport.update({
  id: '/connect/convex',
  path: '/connect/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectGithubRoute = ConnectGithubRouteImport.update({
  id: '/connect/github',
  path: '/connect/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectImessageRoute = ConnectImessageRouteImport.update({
  id: '/connect/imessage',
  path: '/connect/imessage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectXchatRoute = ConnectXchatRouteImport.update({
  id: '/connect/xchat',
  path: '/connect/xchat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hosting': typeof HostingRoute
  '/connect/chatgpt': typeof ConnectChatgptRoute
  '/connect/convex': typeof ConnectConvexRoute
  '/connect/github': typeof ConnectGithubRoute
  '/connect/imessage': typeof ConnectImessageRoute
  '/connect/xchat': typeof ConnectXchatRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hosting': typeof HostingRoute
  '/connect/chatgpt': typeof ConnectChatgptRoute
  '/connect/convex': typeof ConnectConvexRoute
  '/connect/github': typeof ConnectGithubRoute
  '/connect/imessage': typeof ConnectImessageRoute
  '/connect/xchat': typeof ConnectXchatRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hosting': typeof HostingRoute
  '/connect/chatgpt': typeof ConnectChatgptRoute
  '/connect/convex': typeof ConnectConvexRoute
  '/connect/github': typeof ConnectGithubRoute
  '/connect/imessage': typeof ConnectImessageRoute
  '/connect/xchat': typeof ConnectXchatRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hosting'
    | '/connect/chatgpt'
    | '/connect/convex'
    | '/connect/github'
    | '/connect/imessage'
    | '/connect/xchat'
    | '/projects/new'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hosting'
    | '/connect/chatgpt'
    | '/connect/convex'
    | '/connect/github'
    | '/connect/imessage'
    | '/connect/xchat'
    | '/projects/new'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/hosting'
    | '/connect/chatgpt'
    | '/connect/convex'
    | '/connect/github'
    | '/connect/imessage'
    | '/connect/xchat'
    | '/projects/new'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostingRoute: typeof HostingRoute
  ConnectChatgptRoute: typeof ConnectChatgptRoute
  ConnectConvexRoute: typeof ConnectConvexRoute
  ConnectGithubRoute: typeof ConnectGithubRoute
  ConnectImessageRoute: typeof ConnectImessageRoute
  ConnectXchatRoute: typeof ConnectXchatRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/chatgpt': {
      id: '/connect/chatgpt'
      path: '/connect/chatgpt'
      fullPath: '/connect/chatgpt'
      preLoaderRoute: typeof ConnectChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/convex': {
      id: '/connect/convex'
      path: '/connect/convex'
      fullPath: '/connect/convex'
      preLoaderRoute: typeof ConnectConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/github': {
      id: '/connect/github'
      path: '/connect/github'
      fullPath: '/connect/github'
      preLoaderRoute: typeof ConnectGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/imessage': {
      id: '/connect/imessage'
      path: '/connect/imessage'
      fullPath: '/connect/imessage'
      preLoaderRoute: typeof ConnectImessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/xchat': {
      id: '/connect/xchat'
      path: '/connect/xchat'
      fullPath: '/connect/xchat'
      preLoaderRoute: typeof ConnectXchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostingRoute: HostingRoute,
  ConnectChatgptRoute: ConnectChatgptRoute,
  ConnectConvexRoute: ConnectConvexRoute,
  ConnectGithubRoute: ConnectGithubRoute,
  ConnectImessageRoute: ConnectImessageRoute,
  ConnectXchatRoute: ConnectXchatRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
