/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d78258a2982191c89dbd5e60a9a5caec)
interface __BaseEnv_Env {
	SITE_ASSETS: R2Bucket;
	CONVEX_SITE_HOST_URL: "https://wry-meerkat-833.convex.site/v1/site-host/broker";
	SITES_BASE_DOMAIN: "ichef-sites.buddytools.org";
	CONTROL_PLANE: Fetcher /* ichef-control-plane */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONVEX_SITE_HOST_URL" | "SITES_BASE_DOMAIN">> {}
}
