/// <reference types="vite/client" />
import { auth } from "@clerk/tanstack-react-start/server";
import { HeadContent, Outlet, Scripts, createRootRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import type { ReactNode } from "react";

import { Providers } from "~/components/providers";
import appCss from "~/styles/app.css?url";

const fetchAuth = createServerFn({ method: "GET" }).handler(async () => {
  const { userId } = await auth();
  return { userId };
});

export const Route = createRootRoute({
  beforeLoad: () => fetchAuth(),
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "Launchpad — Built with iChef" },
      {
        name: "description",
        content: "A secure TanStack Start, Clerk, and Convex application generated by iChef.",
      },
      { name: "theme-color", content: "#020617" },
    ],
    links: [{ rel: "stylesheet", href: appCss }],
  }),
  component: () => <Outlet />,
  shellComponent: RootDocument,
});

function RootDocument({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <Providers>{children}</Providers>
        <Scripts />
      </body>
    </html>
  );
}
